import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Link } from 'react-router-dom'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Hello from Next!</h1>
    </div>
  )
}
